//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriesLink
    {
        public int id { get; set; }
        public int parentId { get; set; }
        public int childId { get; set; }
    
        public virtual Category Child { get; set; }
        public virtual Category Parent { get; set; }
    }
}
