//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string userId { get; set; }
        public Nullable<int> itemId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> price { get; set; }
        public string description { get; set; }
        public int deliveryId { get; set; }
        public Nullable<int> state { get; set; }
        public string supplierTitle { get; set; }
        public string supplierAddress { get; set; }
        public Nullable<int> partNumber { get; set; }
        public string supplierCaption { get; set; }
        public string itemTitle { get; set; }
        public string itemImage { get; set; }
        public int count { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Item Item { get; set; }
    }
}
